### ISSUE TITLE
Missing high-lever sort on queries

### ISSUE THREAD

**Issue by jonasmalacofilho** [MattTuttle/mongo-haxe-driver#17]
Although already possible, by creating a query document with [modifiers][],
```haxe
find({ "$query" : { name : "John" }, { "$orderBy" : { age : 1 } } })
```
there should be a higher level method of doing this.

It could be implemented by simply adding a parameter to `find()`, but I think it would be best to implement this in the cursor, so that the official syntax
```haxe
find({ name : "John" }).sort({ age : 1 })
```
can be supported.

In the latter case it would also be necessary to defer the query execution to the cursor—like done in the [Java][] driver—and delay it to the moment of the first `hasNext` or `next()` calls.

I'll be happy to implement this some other time, if no one has done it by then.

[modifiers]:http://docs.mongodb.org/manual/reference/operator/query-modifier/
[Java]:https://github.com/mongodb/mongo-java-driver/blob/master/src/main/com/mongodb/DBCursor.java#L202

**Comment by MattTuttle** [comment]
Implemented in #20.
