### ISSUE TITLE
Travis: enable CI for pull requests

### ISSUE THREAD

**Issue by jonasmalacofilho** [MattTuttle/mongo-haxe-driver#23]
Although I already have Travis set up for my fork, I think it would be benneficial for most collaborators if you enabled CI tests for pull requests.

**Comment by MattTuttle** [comment]
Travis-CI shows that pull requests are already enabled.

**Comment by jonasmalacofilho** [comment]
Weirdly, Travis CI hasn't run for #24 either.

**Comment by MattTuttle** [comment]
This is the only setting I can find for pull requests. :(
![screen shot 2015-01-07 at 10 09 33 pm](https://cloud.githubusercontent.com/assets/620357/5657760/e23554a8-96b9-11e4-8239-de2b3f4e8880.png)

**Comment by jonasmalacofilho** [comment]
Maybe the issue is related to the fact that those exact merge commits had already been tested in my repository (which is separately set-up on Travis CI). But other merges do seem to trigger a build (see #25), so I'll close this.
